name: linting workflow
on: 
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: action/checkout@v4
              
